dist: trusty

cache:
  directories:
    - node_modules

language: node_js

node_js:
- '8.4.0'

addons:
  chrome: stable
  apt:
    packages:
      - oracle-java8-set-default

script: ./scripts/travis.sh

install:
- npm install

before_install:
- "npm install -g npm@5.6.0"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start" # the starting the virtual X frame buffer: Xvfb process
  - sleep 3 #wait a while before xvfb to start
